export const ADMIN = {
  title: "Admin",
  menuLabel: "Admin menu",
  menu: { overview: "Overview", proposals: "Proposals", projects: "Projects", featured: "Featured", events: "Events", people: "People" },
  common: {
    edit: "Edit", hide: "Hide", show: "Show", delete: "Delete", save: "Save", cancel: "Cancel",
    add: "Add", remove: "Remove", search: "Search", all: "All",
    public: "public", hidden: "hidden", you: "you", loading: "Loading...",
  },

  overview: {
    title: "Overview",
    proposals: "Proposals waiting",
    hidden: "Hidden projects",
    offline: "Sites offline",
    events: "Upcoming events",
    sync: "Last sync with GitHub",
    never: "Never",
    error: "Could not load the numbers.",
  },

  proposals: {
    title: "Proposals",
    empty: "No proposals are waiting.",
    by: (name: string) => `by ${name}`,
    source: "Source",
    approve: "Approve",
    reject: "Reject",
    delete: "Delete",
    loadFailed: "Could not load proposals.",
    approved: (name: string) => `Approved "${name}".`,
    approveFailed: (name: string) => `Could not approve "${name}".`,
    rejected: (name: string) => `Rejected "${name}".`,
    rejectFailed: (name: string) => `Could not reject "${name}".`,
    deleteConfirm: (name: string) => `Delete the proposal "${name}"? This cannot be undone.`,
    deleted: (name: string) => `Deleted "${name}".`,
    deleteFailed: "Could not delete the proposal.",
  },

  projects: {
    title: "Projects",
    search: "Search projects",
    filters: [["all", "All"], ["public", "Public"], ["hidden", "Hidden"], ["needs_maintainers", "Needs a maintainer"], ["archived", "Archived"]] as [string, string][],
    empty: "No projects match.",
    loadFailed: "Could not load projects.",
    visibilityFailed: "Could not change this project.",
    nowPublic: (name: string) => `"${name}" is now public.`,
    nowHidden: (name: string) => `"${name}" is now hidden.`,
    deleteConfirm: (name: string) => `Delete "${name}"? Its maintainers, notes and featured entry are deleted too. Events stay.`,
    deleted: (name: string) => `Deleted "${name}".`,
    deleteFailed: "Could not delete the project.",
    noDescription: "No description",
    importTitle: "Import from GitHub",
    importHelp: "Lists public repositories of the organization that are not on the site yet. Forks are skipped. Private repositories do not show here. Add those from a proposal.",
    load: "Load repositories",
    reload: "Reload repositories",
    loadingRepos: "Loading...",
    publishNow: "Make public right away",
    allImported: "Every public repository is already on the site.",
    import: "Add",
    archived: "archived",
    noOrg: (org: string) => `GitHub has no organization called "${org}". Check src/config.ts.`,
    rateLimit: "GitHub is blocking requests for now. Try again in an hour.",
    githubError: (code: number) => `GitHub returned an error (${code}).`,
    unreachable: "Could not reach GitHub.",
    importFailed: (name: string) => `Could not add "${name}". A project with this name may already exist.`,
    imported: (name: string, isPublic: boolean) =>
      isPublic ? `Added "${name}".` : `Added "${name}" as hidden. Fix the description, then make it public.`,
  },

  featured: {
    title: "Featured",
    help: "These projects show on the home page, in this order. Only public projects can be featured.",
    empty: "Nothing is featured yet.",
    name: "Name",
    usage: "What is it used for?",
    screenshot: "Screenshot link (optional)",
    project: "Project",
    chooseProject: "Choose a project",
    addTitle: "Add a featured project",
    addButton: "Add",
    up: "Up",
    down: "Down",
    loadFailed: "Could not load featured projects.",
    saved: (name: string) => `Saved "${name}".`,
    saveFailed: "Could not save.",
    orderFailed: "Could not save the new order.",
    removeConfirm: (name: string) => `Remove "${name}" from the home page? The project stays.`,
    removed: "Removed.",
    removeFailed: "Could not remove it.",
    missing: "Choose a project and fill in the name and the text.",
    added: "Added.",
    addFailed: "Could not add it. It may already be featured.",
  },

  events: {
    title: "Events",
    addTitle: "Add an event",
    editTitle: "Edit event",
    name: "Name",
    when: "Date and time (your time zone)",
    where: "Place",
    description: "Description",
    link: "Link to register or join",
    project: "Related project (optional)",
    none: "None",
    saveAdd: "Add event",
    saveEdit: "Save changes",
    listTitle: "All events",
    empty: "No events yet.",
    upcoming: "upcoming",
    past: "past",
    required: "A name and a date are required.",
    saved: "Event saved.",
    saveFailed: "Could not save the event.",
    visibilityFailed: "Could not change this event.",
    nowHidden: "Event hidden.",
    nowPublic: "Event is public.",
    deleteConfirm: (title: string) => `Delete "${title}"?`,
    deleted: "Deleted.",
    deleteFailed: "Could not delete the event.",
  },

  people: {
    title: "People",
    adminsTitle: "Admins",
    adminsHelp: "Admins can do everything on this page. Give the role to as few people as you can. You cannot remove yourself.",
    othersTitle: "Others who signed in",
    othersEmpty: "No one else has signed in yet.",
    search: "Search by GitHub username",
    makeAdmin: "Make admin",
    removeAdmin: "Remove",
    loadFailed: "Could not load people.",
    added: (name: string) => `${name} is now an admin.`,
    addFailed: "Could not make this person an admin.",
    removeConfirm: (name: string) => `Remove ${name} as admin? They keep their maintainer roles.`,
    removed: (name: string) => `${name} is no longer an admin.`,
    removeFailed: "Could not remove this admin.",
    unknown: "unknown",
  },
};
